name: vocabulary_and_translation_gui

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python ==3.11
  - pip >=21.1
  - setuptools_scm
  - toml

  # Reproducibility
  - conda-lock

  # Package dependencies
  - pytask >=0.2

  # Misc
  - black
  - ipython
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda

  # Documentation
  - furo
  - myst-parser
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-copybutton
  - sphinx-panels

  - pip:
    - -e .
    - sphinxext-opengraph
    - deepl >= 1.14.0
    - pyenchant >= 3.2.2
    - genanki >= 0.13.0
    - openpyxl >= 3.1.2
    - pandas >= 1.5.3
    - pytask-latex >= 0.3.0